###
GET http://localhost:3000/v1/classic/latest
Accept: application/json

###
GET http://localhost:3000/v1/book/latest
Accept: application/json
###

POST http://localhost:3000/v1/8/classic/latest
Accept: application/json

###
POST http://localhost:3000/v1/user/register HTTP/1.1

{
  "nickname": "莫按摩",
  "password1": "111111$$",
  "password2": "111111$$",
  "email": "111abc111@qq.com"
}

###
